#!/bin/bash

outAcpi=$(acpi)
INFO=$(echo $outAcpi | cut -d':' -f2)


STATE=$(echo "$INFO" | grep -o "Charging")
LEVEL_PRCNTS=$(echo "$INFO" | grep -o '[0-9]\+%')
LEVEL=${LEVEL_PRCNTS:: -1} #Battery 0: Unknown, 99%

if ! [[ "$LEVEL" -lt 101 ]]; then
    LEVEL=${LEVEL_PRCNTS:: -4}
#Battery 0: Unknown, 99%
#Battery 1: Unknown, 0%, rate information unavailable
fi



MAIN_COLOR="#74AEAB"
ICON_COLOR=$MAIN_COLOR


if [[ "$LEVEL" -ge 80 ]];   then ICON=""
elif [[ "$LEVEL" -ge 60 ]]; then ICON=""
elif [[ "$LEVEL" -ge 40 ]]; then ICON=""
elif [[ "$LEVEL" -ge 20 ]]; then ICON=""
elif [[ "$LEVEL" -lt 20 ]]; then
    ICON=""
    ICON_COLOR="red"
    #echo "$((LEVEL - 20))"
fi



if [[ "$(echo "$INFO" | grep -o "Charging")" ]]; then ICON_COLOR="green"; fi

#if [[ "$BLOCK_BUTTON" == 1 ]]; then TEXT="<span color='$MAIN_COLOR'>$LEVEL_PRCNTS</span>"; fi
if [[ "$BLOCK_BUTTON" == 1 ]]; then TEXT="<span color='$MAIN_COLOR'>$(echo "$INFO" | grep -o [0-9][0-9]:[0-9][0-9]:[0-9][0-9])</span>"; fi

#echo "$TEXT"
#echo "$LEVEL"
echo "<span color='$ICON_COLOR'>$ICON $LEVEL%</span> "$TEXT

